### ISSUE TITLE
borrowing content from 454/491 assignments

### ISSUE THREAD

**Issue by sonatata** [dcsil/CSC491#12]
**Describe the concern**
So 491 and 454 assignments tend to overlap on a lot of topics especially A2 454 (part 2 market research section) and A3 491 (Product & Research folders section)  and we tend to have the same answers for many of the requirements in both assignment sections. 
For example, A2-454 asks us to describe the market, target market, etc and A3-491 sort of does the same...
Do we restate the same content or should we be tackling the 491 assignment in a different lens? 

**Why is this important?**
I would like to make sure that I understood the assignment requirement correctly :) 

**Ideal solution**
It would be nice to re-use the content we created in the 454 assignment assuming they're both asking for the same thing.

**Comment by jules2689** [comment]
Feel free to re-use the content! It would be great to put an engineering spin where it makes sense, and otherwise put a product management spin on 491 content rather than strictly business! 😄

**Comment by sonatata** [comment]
Great! Thanks for clarifying 😄
