### ISSUE TITLE
Creating ML Models/Using Dessa

### ISSUE THREAD

**Issue by DanielChanJA** [dcsil/CSC491#14]
Just looking at our group's problem space and the way that we're looking to solve it, would it be possible to use a pre-existing ML model that's already out there that already does what we're trying to analyze?

(I.E we're trying to perform sentiment analysis on text, but there's already tons of models out there, that's not including APIs such as Microsoft's Cognitive API, Google's Natural Language API and Grammarly's own implementation of sentiment analysis)

I'm just trying to avoid going down the black hole that is creating a ML model that is going to yield decent results, whereas we could be implementing other features for the MVP.

**Comment by jules2689** [comment]
Follow any licenses. https://choosealicense.com/ can help you understand restrictions.
As long as you don't violate licenses as you may commercialize your idea, then go ahead 😄

**Comment by DanielChanJA** [comment]
Perfect, thanks for the speedy response! @jules2689 Does this mean we're also able to use the various APIs that Microsoft/Google/Grammarly have?

**Comment by jules2689** [comment]
For sure! This is a startup, so if you commercialize you'll have to worry about contracts, licensing, and cost. But for an MVP, I wouldnt worry too much as you'll likely be in the free bucket!

The other stuff to consider is many terms of services will say that they can use your data. So they make money/profit off of getting datasets on top of being paid! This is especially noticeable on free plans, as this is how they make $.

**Comment by DanielChanJA** [comment]
Perfect! Thanks alot! Hope SF's weather is better than Toronto's!

**Comment by jules2689** [comment]
hah it's about the same. Kinda cold here tbh
