### ISSUE TITLE
A1 submission clarification 

### ISSUE THREAD

**Issue by EndBird** [dcsil/CSC491#9]
**Describe the concern**
In A1.md, it says The body of the release must include a list of Pull Requests (at least one from every member) that has reviews.

What does it mean by "has reviews"? How do we know that there are reviews

**Why is this important?**
Its part of A1 requirement

**Comment by jules2689** [comment]
I originally intended for everyone to use https://help.github.com/en/articles/about-pull-request-reviews

But since we ended up with only one CSC491 per team (on average), ignore that requirement.
If you _did_ end up with 2 CSC491, please have both of them submit :)

cc @dcsil/csc491-f19
